export const products=[
    {
      id:1,
      name:'Maquina manual',
      price: 120,
      weight:'COD: SB04A',
      image: '1.png',
      available: true,
      amount: 1,
      subtotal: 0,
    },
    {
      id:2,
      name:'Maquina Manual',
      price: 140,
      weight:'COD: ST-130',
      image: '2.png',
      available: true,
      amount: 1,
      subtotal: 0,
      
    },
    {
      id:3,
      name:'Maquina Doble Estacion',
      price: 170,
      weight:'COD: ST-210',
      image: '3.png',
      available: true,
      amount: 1,
      subtotal: 0,
    },
    {
      id:4,
      name:'Maquina Multifuncional 8-1',
      price: 350,
      weight:'COD: ST-220',
      image: '4.png',
      available: true,
      amount: 1,
      subtotal: 0,
    },
    {
      id:5,
      name:'Maquina Multifuncional 8-1',
      price: 390,
      weight:'COD: ST-220',
      image: '5.png',
      available: true,
      amount: 1,
      subtotal: 0,
    },
    {
      id:6,
      name:'Maquina Multifuncional 11-1',
      price: 490,
      weight:'COD: P8200-V11',
      image: '6.png',
      available: true,
      amount: 1,
      category: 'Grano',
      subtotal: 0,
    },
    {
      id:7,
      name:'Maquina Multifuncional 5-1',
      price: 420,
      weight:'COD: SB04W',
      image: '7.png',
      available: true,
      amount: 1,
      category: 'Grano',
      subtotal: 0,
    },
    {
      id:8,
      name:'Maquina de Gorras 2-1',
      price: 260,
      weight:'Resistencia cuadrada',
      image: '8.png',      
      available: true,
      amount: 1,
      category: 'Grano',
      subtotal: 0,
    },
  ];