export const products=[
    {
      id:1,
      name:'Maquina manual',
      price: 120,
      weight:'cod: SB04A',
      image: '1.png',
      available: true,
      amount: 1,
      subtotal: 0,
    },
    {
      id:2,
      name:'Café Tostado Molido',
      price: 140,
      weight:'500 Gr',
      image: '2.png',
      available: true,
      amount: 1,
      subtotal: 0,
      
    },
    {
      id:3,
      name:'Café Tostado Molido',
      price: 170,
      weight:'1000 Gr',
      image: '3.png',
      available: true,
      amount: 1,
      subtotal: 0,
    },
    {
      id:4,
      name:'Café Tostado en Grano',
      price: 350,
      weight:'250 Gr',
      image: '4.png',
      available: true,
      amount: 1,
      subtotal: 0,
    },
    {
      id:5,
      name:'Café Tostado en Grano',
      price: 390,
      weight:'500 Gr',
      image: '5.png',
      available: true,
      amount: 1,
      subtotal: 0,
    },
    {
      id:6,
      name:'Café Tostado en Grano',
      price: 490,
      weight:'1000 Gr',
      image: '6.png',
      available: true,
      amount: 1,
      category: 'Grano',
      subtotal: 0,
    },
    {
      id:7,
      name:'Granos de Café Seco',
      price: 420,
      weight:'250 Gr',
      image: '7.png',
      available: true,
      amount: 1,
      category: 'Grano',
      subtotal: 0,
    },
    {
      id:8,
      name:'Granos de Café Seco',
      price: 260,
      weight:'500 Gr',
      image: '8.png',      
      available: true,
      amount: 1,
      category: 'Grano',
      subtotal: 0,
    },
    {
      id:9,
      name:'Granos de Café Seco',
      price: 92000,
      weight:'1000 Gr',
      image: '1.png',
      available: true,
      amount: 1,
      subtotal: 0,
    },
   
   
  ];